name: Test Frontmatter Content

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 22
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: 'npm'
        - name: Install Dependencies
          run: npm ci
        - name: Test Frontmatter Content
          run: npm run test:frontmatter
